//
// Created by adiog on 12/18/16.
//

#ifndef CPP_THREAD_FILEDESCRIPTOROUTPUTWRITERSTREAM_H
#define CPP_THREAD_FILEDESCRIPTOROUTPUTWRITERSTREAM_H

#endif //CPP_THREAD_FILEDESCRIPTOROUTPUTWRITERSTREAM_H
